"""Re-synchronize schema

Revision ID: 843fcc0c314d
Revises: d4416522705e
Create Date: 2024-11-13 12:29:30.939474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843fcc0c314d'
down_revision = 'd4416522705e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False, server_default=''))

    # Remove the default value after adding the column, if desired
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('password', server_default=None)

    # ### end Alembic commands ###


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
